apiVersion: v1
kind: Service
metadata:
  name: bhasha-client
  namespace: bhasha
  labels:
    app: bhasha
    component: client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: bhasha
    component: client
