apiVersion: v1
kind: Service
metadata:
  name: bhasha-server
  namespace: bhasha
  labels:
    app: bhasha
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: bhasha
    component: server
