apiVersion: v1
kind: Service
metadata:
  name: Bhasha-server
  namespace: Bhasha
  labels:
    app: Bhasha
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: Bhasha
    component: server
