apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: Bhasha-server-pdb
  namespace: Bhasha
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: Bhasha
      component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: Bhasha-client-pdb
  namespace: Bhasha
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: Bhasha
      component: client
